apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  namespace: default
spec:
  tls:
    - hosts:
      - httpbin-latest.cndy.org
      secretName: cndy-tls
  rules:
    - host: httpbin-latest.cndy.org
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: httpbin-latest-svc
              port:
                number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-latest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-latest
      author: wanglijuan
  template:
    metadata:
      labels:
        app: httpbin-latest
        author: wanglijuan
    spec:
      containers:
        - name: httpbin-latest
          image: kennethreitz/httpbin:latest

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-latest-svc
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
     app: httpbin-latest
     author: wanglijuan
